# Задача 1. «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [6]:
def vstavka(arr, length):
    for i in range(length):
        key= arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
        
def Perimetr(a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
length = int(input('Введите длину массива'))
massive=[]
for i in range(length):
    massive.append(int(input()))
vstavka(massive, length)
for i in range(length-2):
    if Perimetr(massive[i], massive[i+1], massive[i+2])>0:
        print("Периметр=", Perimetr(massive[i], massive[i+1], massive[i+2]))
        break  

Введите длину массива5
1
4
3
2
5
Периметр= 9


# Задача 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число.

In [18]:
a = [8308,830,8308]
b = [90,9]
c = [50,2,1,9]
d = [999991,9,98]
def fractionalize(i):
    divisor = 9
    while divisor < i:
        divisor = 10 * divisor + 9 

    return i / divisor
print(sorted(a, key=fractionalize, reverse=True))
print(sorted(b, key=fractionalize, reverse=True))
print(sorted(c, key=fractionalize, reverse=True))
print(sorted(d, key=fractionalize, reverse=True))

[8308, 8308, 830]
[9, 90]
[9, 50, 2, 1]
[9, 999991, 98]


# Задача 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения  целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [10]:
import numpy
def per_mas(n, m):
    for i in range(n):
        for j in range(m):
            yield i, j
m, n= map(int, input('Введите m и n:').split(' '))
mass = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i, j in per_mas(len(mass[0]), len(mass)):
    k=j
    l=i
    while k<len(mass[0]) and l<len(mass):
        if mass[i][j]>mass[l][k]:
            mass[i][j], mass[l][k]=mass[l][k], mass[i][j]
        k=k+1
        l=l+1
            
print("\n ================ \n")
print(mass)

Введите m и n:5 5
[[ 1  1  0 10  3]
 [ 6  6  2  7 16]
 [ 5 12  7  8 17]
 [ 7  9 14  8 18]
 [20 17 20 16 15]]


[[ 1  7  7  5  6]
 [ 2 10  8  7 11]
 [10  4 14  8 17]
 [ 0 10  7 16 14]
 [ 1 18 15 15 20]]


<ipython-input-10-e9f5b93665a5>:7: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  mass = numpy.random.random_integers(0, 20, size=(m, n))
