# Курсовая работа №1 по дисциплине СиАОД

## Выполнил студент группы БСТ1903 Самоваров А.П.

### Задание 1 - Треугольник с максимальным периметром

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [6]:
def vstavka(arr, length):
    for i in range(length):
        key= arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
        
def Perimetr(a, b, c):
    if (a+b)>c and (a+c)>b and (b+c)>a:
        return int(a+b+c)
    else:
        return 0
length = int(input('Введите длину массива '))
massive=[]
for i in range(length):
    massive.append(int(input()))
vstavka(massive, length)
for i in range(length-2):
    if Perimetr(massive[i], massive[i+1], massive[i+2])>0:
        print("Периметр=", Perimetr(massive[i], massive[i+1], massive[i+2]))
        break  

Введите длину массива5
1
4
3
2
5
Периметр= 9


## Задание 2 - Максимальное число
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число.

In [11]:
def generateArr_2(size):
    if size<1: size=1
    elif size>100: size=100
    arr=[]
    for i in range(size):
        arr.append(random.randint(0,10**9))
    return arr
 
#Функция возвращает true, если первое число больше второго
def value1_bigger(int_val1, int_val2):
    val1=str(int_val1)
    val2=str(int_val2)


    if int(val1+val2)>int(val2+val1):
        return True
    else:
        return False


In [13]:
def exercise_2():
    arr=[8308,830,8308]

    print('Исходный массив:\n\n A =',arr)
    max_val=""

    for i in range(len(arr)-1):
        max_elem=arr[i]
        max_index=i

        for j in range(i+1, len(arr)):
            if value1_bigger(arr[j],max_elem):
                max_elem=arr[j]
                max_index=j

        arr[max_index],arr[i]=arr[i],arr[max_index]

    for i in range(len(arr)):
        max_val+=str(arr[i])

    print("\nОтсортированный массив:\n\n A =",arr)
    print("\nМаксимально возможное число:\n\n",max_val)
exercise_2()

Исходный массив:

 A = [8308, 830, 8308]

Отсортированный массив:

 A = [8308, 8308, 830]

Максимально возможное число:

 83088308830


## Задание 3 - Сортировка диагоналей в матрице
Дана матрица mat размером m * n, значения  целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [10]:
import numpy
def per_mas(n, m):
    for i in range(n):
        for j in range(m):
            yield i, j
m, n= map(int, input('Введите m и n:').split(' '))
mass = numpy.random.random_integers(0, 20, size=(m, n))
print(massiv)
for i, j in per_mas(len(mass[0]), len(mass)):
    k=j
    l=i
    while k<len(mass[0]) and l<len(mass):
        if mass[i][j]>mass[l][k]:
            mass[i][j], mass[l][k]=mass[l][k], mass[i][j]
        k=k+1
        l=l+1
            
print("\n ================ \n")
print(mass)

Введите m и n:5 5
[[ 1  1  0 10  3]
 [ 6  6  2  7 16]
 [ 5 12  7  8 17]
 [ 7  9 14  8 18]
 [20 17 20 16 15]]


[[ 1  7  7  5  6]
 [ 2 10  8  7 11]
 [10  4 14  8 17]
 [ 0 10  7 16 14]
 [ 1 18 15 15 20]]


<ipython-input-10-e9f5b93665a5>:7: DeprecationWarning: This function is deprecated. Please call randint(0, 20 + 1) instead
  mass = numpy.random.random_integers(0, 20, size=(m, n))


## Задания со строками

### Задание 4

Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.


In [24]:
def zadacha_1(str1, str2):
    st1=list(str1)
    st2=list(str2)
    l=len(st1)
    st1.sort()
    st2.sort()
    i=0
    if len(st1)!= len(st2):
        return "Not equal length of strings"
    while i<l and st1[i]==st2[i]:
        i+=1
    if i == l:
        return True
    if st1[0]>st2[0]:
        for k in range(len(st1)):
            if(st1[k]<st2[k]):
                return False
        return True
    else:
        for k in range(len(st2)):
            if(st2[k]<st1[k]):
                return False
        return True


zadacha_1('abechdgf','acdyquef')

True

### Задание 5

Дана строка s, вернуть самую длинную полиндромную подстроку в s

In [35]:
def palindrome(x):
    if len(x) <= 1: 
        return False
    return x == x[::-1] 
def zadacha_2(s):
    last = len(s)
    lst = [] 
    for i in range(last):
        for j in range(i, last): 
            b = s[i:j+1] 
            if palindrome(b):
                lst.append(b)
    return lst[0] 
st = input("Введите строку: ")
print("Самая длинная палиндромная строка:")
print(zadacha_2(st))

Введите строку: кусььсук
Самая длинная палиндромная строка:
кусььсук


### Задача 6

Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).


In [45]:
def zadanie_3(str1):
    rez=set()
    for i in range(len(str1)-1):
        k=i
        for j in range(i+1, len(str1)):
            l=j
            m=j
            while l<len(str1) and k<m and str1[k]==str1[l]:
                k+=1
                l+=1
            if k==m:
                rez.add(str1[i:l])
                break
    return len(rez), rez

zadanie_3("abcabcabc")

(3, {'abcabc', 'bcabca', 'cabcab'})

### Задание 7 - Интервалы

Дан массив отрезков intervals, в котором intervals[i] = [starti
, endi
], некоторые
отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезков.

In [46]:
def intervals(interv):
    interv.sort()
    i=0
    while i <len(interv)-1:
        if interv[i][1]>=interv[i+1][0]:
            a=interv.pop(0)
            b=interv.pop(0)
            interv.insert(0, [a[0],b[1]])
        else:
            i+=1
    return interv

intervals( [[1,4],[4,5]])

[[1, 5]]

### Задание 8 - Монетки

На столе стоят 3n стопок монет. Вы и ваши друзья Алиса и Боб забираете стопки монет по
следующему алгоритму:
1. Вы выбираете 3 стопки монет из оставшихся на столе.
2. Алиса забирает себе стопку с максимальным количеством монет.
3. Вы забираете одну из двух оставшихся стопок.
4. Боб забирает последнюю стопку.
5. Если еще остались стопки, то действия повторяются с первого шага

In [37]:
def moneti(arr):
    arr.sort()
    a=len(arr)//3
    s=0
    while a<len(arr):
        s=s+arr[a]
        a=a+2
    return (s)

moneti ( [9,8,7,6,5,1,2,3,4])

18

## Задание 9 - Шарики и стрелы

Некоторые сферические шарики распределены по двухмерному пространству. Для каждого шарика даны xкоординаты начала и конца его горизонтального диаметра. Так как пространство двумерно, то yкоординаты не имеют значения в данной задаче. Координата xstart всегда меньше xend. Стрелу можно выстрелить строго вертикально (вдоль yоси) из разных точек xоси. Шарик с координатами xstart и xend уничтожается стрелой, если она была выпущена из такой позиции x, что xstart ⩽ x ⩽ xend. Когда стрела выпущена, она летит в пространстве бесконечное время (уничтожая все шарики на пути). Дан массив points, где points[i] = [xstart, xend]. Напишите функцию, возвращающую минимальное количество стрел, которые нужно выпустить, чтобы уничтожить все шарики.

In [43]:
class sh:
    def __init__(self, mass):
        self.mass=mass
        self.count=1
    
    def search(self):
        if len(self.mass)==0:
            self.count=0
        else:
            m=0
            for i in range(len(self.mass)):
                self.mass.sort()
            print(self.mass)
            for i in range(len(self.mass)-1):
                if self.mass[m][1]<self.mass[i+1][0]:
                    self.count=self.count+1
                    m=i+1
                elif self.mass[m][0]<=self.mass[i+1][0] and self.mass[m][1]>=self.mass[i+1][1]:
                       m=i+1
                    
        return self.count
            
mass=[[9,12],[1,10],[4,11],[8,12],[3,9],[6,9],[6,7]]           
a=sh(mass)
print(a.search())

[[1, 10], [3, 9], [4, 11], [6, 7], [6, 9], [8, 12], [9, 12]]
2


# Вывод

В ходе проделанной работы были выполнены задачи на нахождение максимального периметра, максимального числа, сортировки диагоналей, 3 задачи по работе со строками, монетки, интервалы а также шарики и стрелы